// =============================================================================
// Animation Export — zero dependencies
// Converts the internal TaggedElement[] data model to multiple output formats.
// =============================================================================

import type { TaggedElement, ExportFormat } from "./motion-types";

export function exportAnimation(
  elements: TaggedElement[],
  format: ExportFormat
): string {
  if (elements.length === 0) return "/* No elements tagged */";
  switch (format) {
    case "css":
      return exportToCSS(elements);
    case "waapi":
      return exportToWAAPI(elements);
    case "framer-motion":
      return exportToFramerMotion(elements);
    case "gsap":
      return exportToGSAP(elements);
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function camelToKebab(str: string): string {
  return str.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function makeKeyframeId(label: string, phase: string): string {
  const slug = label
    .replace(/[^a-z0-9]/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
  return `agentation-${slug}-${phase}`;
}

function phaseGlobalDelay(el: TaggedElement, phase: "enter" | "idle" | "exit"): number {
  const enterTotal = el.enter.duration + el.enter.delay;
  if (phase === "enter") return el.startTime + el.enter.delay;
  if (phase === "idle") return el.startTime + enterTotal + el.idle.delay;

  // exit — after idle (if idle is finite)
  if (!el.idle.enabled) return el.startTime + enterTotal + el.exit.delay;
  const idleIter =
    el.idle.iterations === "infinite" ? 1 : Number(el.idle.iterations);
  return el.startTime + enterTotal + el.idle.duration * idleIter + el.idle.delay + el.exit.delay;
}

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

function keyframesToCSS(keyframes: Keyframe[]): string {
  if (!keyframes.length) return "";
  if (keyframes.length === 2 && keyframes[0].offset == null && keyframes[1].offset == null) {
    const from = Object.entries(keyframes[0])
      .filter(([k]) => k !== "offset")
      .map(([k, v]) => `${camelToKebab(k)}: ${v};`)
      .join(" ");
    const to = Object.entries(keyframes[1])
      .filter(([k]) => k !== "offset")
      .map(([k, v]) => `${camelToKebab(k)}: ${v};`)
      .join(" ");
    return `  from { ${from} }\n  to { ${to} }`;
  }
  return keyframes
    .map((kf, i) => {
      const offset = kf.offset != null ? Number(kf.offset) : i / (keyframes.length - 1);
      const pct = `${Math.round(offset * 100)}%`;
      const props = Object.entries(kf)
        .filter(([k]) => k !== "offset")
        .map(([k, v]) => `${camelToKebab(k)}: ${v};`)
        .join(" ");
      return `  ${pct} { ${props} }`;
    })
    .join("\n");
}

function exportToCSS(elements: TaggedElement[]): string {
  const lines: string[] = ["/* Generated by Agentation Motion */\n"];

  for (const el of elements) {
    const animationParts: string[] = [];

    const phases = [
      { kind: "enter" as const, phase: el.enter },
      { kind: "idle" as const, phase: el.idle },
      { kind: "exit" as const, phase: el.exit },
    ];

    for (const { kind, phase } of phases) {
      if (!phase.enabled || !phase.keyframes.length) continue;

      const id = makeKeyframeId(el.label, kind);
      const delay = phaseGlobalDelay(el, kind);
      const iter =
        phase.iterations === "infinite"
          ? "infinite"
          : String(phase.iterations);

      lines.push(`/* ${el.label} — ${kind} */`);
      lines.push(`@keyframes ${id} {`);
      lines.push(keyframesToCSS(phase.keyframes));
      lines.push(`}\n`);

      animationParts.push(
        `${id} ${phase.duration}ms ${phase.easing} ${delay}ms ${iter} ${phase.direction} both`
      );
    }

    if (animationParts.length > 0) {
      lines.push(`${el.selector} {`);
      if (animationParts.length === 1) {
        lines.push(`  animation: ${animationParts[0]};`);
      } else {
        lines.push(`  animation:`);
        animationParts.forEach((a, i) => {
          lines.push(`    ${a}${i < animationParts.length - 1 ? "," : ";"}`);
        });
      }
      lines.push(`}\n`);
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// WAAPI
// ---------------------------------------------------------------------------

function exportToWAAPI(elements: TaggedElement[]): string {
  const lines: string[] = [
    "/* Generated by Agentation Motion — Web Animations API */\n",
  ];

  for (const el of elements) {
    lines.push(`// ${el.label}`);
    lines.push(
      `const el = document.querySelector(${JSON.stringify(el.selector)});`
    );

    const phases = [
      { kind: "enter" as const, phase: el.enter },
      { kind: "idle" as const, phase: el.idle },
      { kind: "exit" as const, phase: el.exit },
    ];

    for (const { kind, phase } of phases) {
      if (!phase.enabled || !phase.keyframes.length) continue;

      const delay = phaseGlobalDelay(el, kind);
      const iter =
        phase.iterations === "infinite" ? "Infinity" : phase.iterations;

      const opts: Record<string, unknown> = {
        duration: phase.duration,
        delay,
        easing: phase.easing,
        fill: "both",
      };
      if (kind === "idle") {
        opts.iterations = iter;
        opts.direction = phase.direction;
      }

      const kfStr = JSON.stringify(phase.keyframes, null, 2);
      const optsStr = JSON.stringify(opts, null, 2).replace(
        /"Infinity"/g,
        "Infinity"
      );
      lines.push(`el?.animate(`);
      lines.push(`  ${kfStr.replace(/\n/g, "\n  ")},`);
      lines.push(`  ${optsStr.replace(/\n/g, "\n  ")}`);
      lines.push(`); // ${kind}`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Framer Motion
// ---------------------------------------------------------------------------

function cssEasingToFM(easing: string): string | number[] {
  const map: Record<string, string> = {
    ease: "easeInOut",
    "ease-in": "easeIn",
    "ease-out": "easeOut",
    "ease-in-out": "easeInOut",
    linear: "linear",
  };
  return map[easing] ?? easing;
}

function keyframeToFMProps(kf: Keyframe): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(kf)) {
    if (k === "offset" || v === undefined) continue;
    out[k] = v;
  }
  return out;
}

function exportToFramerMotion(elements: TaggedElement[]): string {
  const lines: string[] = [
    "// Generated by Agentation Motion — Framer Motion\n",
  ];

  for (const el of elements) {
    const safe = el.label.replace(/[^a-zA-Z0-9]/g, "");
    const varName = `${safe.charAt(0).toLowerCase() + safe.slice(1)}Variants`;

    lines.push(`// ${el.label}`);
    lines.push(`const ${varName} = {`);

    if (el.enter.enabled && el.enter.keyframes.length >= 2) {
      const initial = keyframeToFMProps(el.enter.keyframes[0]);
      const animate = keyframeToFMProps(
        el.enter.keyframes[el.enter.keyframes.length - 1]
      );
      const delay = phaseGlobalDelay(el, "enter") / 1000;
      const transition: Record<string, unknown> = {
        duration: el.enter.duration / 1000,
        ease: cssEasingToFM(el.enter.easing),
      };
      if (delay > 0) transition.delay = delay;

      lines.push(`  initial: ${JSON.stringify(initial)},`);
      lines.push(
        `  animate: { ...${JSON.stringify(animate)}, transition: ${JSON.stringify(transition)} },`
      );
    }

    if (el.idle.enabled && el.idle.keyframes.length >= 2) {
      const props = el.idle.keyframes.reduce<Record<string, unknown[]>>(
        (acc, kf) => {
          for (const [k, v] of Object.entries(kf)) {
            if (k === "offset" || v === undefined) continue;
            if (!acc[k]) acc[k] = [];
            acc[k].push(v);
          }
          return acc;
        },
        {}
      );
      const idleDelay = phaseGlobalDelay(el, "idle") / 1000;
      const transition: Record<string, unknown> = {
        duration: el.idle.duration / 1000,
        ease: cssEasingToFM(el.idle.easing),
        repeat:
          el.idle.iterations === "infinite" ? "Infinity" : el.idle.iterations,
        repeatType: el.idle.direction === "alternate" ? "mirror" : "loop",
      };
      if (idleDelay > 0) transition.delay = idleDelay;

      const idleStr = JSON.stringify({ ...props, transition }).replace(
        /"Infinity"/g,
        "Infinity"
      );
      lines.push(`  idle: ${idleStr},`);
    }

    if (el.exit.enabled && el.exit.keyframes.length >= 2) {
      const exit = keyframeToFMProps(
        el.exit.keyframes[el.exit.keyframes.length - 1]
      );
      const transition: Record<string, unknown> = {
        duration: el.exit.duration / 1000,
        ease: cssEasingToFM(el.exit.easing),
      };
      lines.push(
        `  exit: { ...${JSON.stringify(exit)}, transition: ${JSON.stringify(transition)} },`
      );
    }

    lines.push(`};\n`);

    const tag = (el.element as HTMLElement).tagName.toLowerCase();
    lines.push(
      `// <motion.${tag} variants={${varName}} initial="initial" animate="animate" exit="exit" />`
    );
    lines.push(
      `// Selector for reference: ${JSON.stringify(el.selector)}\n`
    );
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// GSAP
// ---------------------------------------------------------------------------

function cssEasingToGSAP(easing: string): string {
  const map: Record<string, string> = {
    ease: "power1.inOut",
    "ease-in": "power2.in",
    "ease-out": "power2.out",
    "ease-in-out": "power2.inOut",
    linear: "none",
  };
  return map[easing] ?? easing;
}

function kfToGSAP(kf: Keyframe): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(kf)) {
    if (k === "offset" || v === undefined) continue;
    out[k] = v;
  }
  return out;
}

function exportToGSAP(elements: TaggedElement[]): string {
  const lines: string[] = [
    "// Generated by Agentation Motion — GSAP\n",
    "const tl = gsap.timeline();\n",
  ];

  for (const el of elements) {
    lines.push(`// ${el.label}`);

    if (el.enter.enabled && el.enter.keyframes.length >= 2) {
      const from = kfToGSAP(el.enter.keyframes[0]);
      const to = {
        ...kfToGSAP(el.enter.keyframes[el.enter.keyframes.length - 1]),
        duration: el.enter.duration / 1000,
        ease: cssEasingToGSAP(el.enter.easing),
      };
      const at = phaseGlobalDelay(el, "enter") / 1000;
      lines.push(
        `tl.fromTo(${JSON.stringify(el.selector)}, ${JSON.stringify(from)}, ${JSON.stringify(to)}, ${at});`
      );
    }

    if (el.idle.enabled && el.idle.keyframes.length >= 2) {
      const to = {
        ...kfToGSAP(el.idle.keyframes[el.idle.keyframes.length - 1]),
        duration: el.idle.duration / 1000,
        ease: cssEasingToGSAP(el.idle.easing),
        repeat:
          el.idle.iterations === "infinite" ? -1 : Number(el.idle.iterations) - 1,
        yoyo: el.idle.direction === "alternate",
      };
      const at = phaseGlobalDelay(el, "idle") / 1000;
      lines.push(
        `tl.to(${JSON.stringify(el.selector)}, ${JSON.stringify(to)}, ${at});`
      );
    }

    if (el.exit.enabled && el.exit.keyframes.length >= 2) {
      const to = {
        ...kfToGSAP(el.exit.keyframes[el.exit.keyframes.length - 1]),
        duration: el.exit.duration / 1000,
        ease: cssEasingToGSAP(el.exit.easing),
      };
      const at = phaseGlobalDelay(el, "exit") / 1000;
      lines.push(
        `tl.to(${JSON.stringify(el.selector)}, ${JSON.stringify(to)}, ${at});`
      );
    }

    lines.push("");
  }

  return lines.join("\n");
}
